---
kind: pipeline
type: docker
name: default

steps:
  - name: yamllint
    image: sdesbure/yamllint:latest
    commands:
      - yamllint .drone.yml
  - name: go-test
    image: golang:1.17
    commands:
      - go test
  - name: go-static-check
    image: golang:1.17
    commands:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - staticcheck ./...
